#!/bin/sh
findDrush() {
    local ARGUMENT="$1"
    if [ -z "$ARGUMENT" ]; then
        local path=$(pwd)
        echo path pwd $path
    else
        local path="$ARGUMENT"
    fi

    # Check if the vendor/bin/drush directory exists in the current directory
    drushDir="$path/vendor/bin/drush"
    if [ -e "$drushDir" ]; then
        # Drush found, return the current directory
        echo "$drushDir"
        return
    fi

    # Move one level up the directory tree
    parentDir=$(dirname "$path")
    if [ "$parentDir" == "$path" ]; then
        # If we reached the root directory, stop traversing
        return
    fi

    # Check if the vendor/bin/drush directory exists in the parent directory
    drushDir="$parentDir/vendor/bin/drush"
    if [ -e "$drushDir" ]; then
        # Drush found in the parent directory, return the parent directory
        echo "$drushDir"
        return
    fi

    # Recursively continue searching in the parent directory
    findDrush "$parentDir"
}

args="$*"

COMMAND_ARGUMENTS="--root= --root -r= -r"
for CURRENT_SUBSTRING in ${COMMAND_ARGUMENTS}; do
    ROOT_HERE=0
    for CURRENT_LINE in ${args}; do
        if [ "$ROOT_HERE" = "1" ]; then
            drupalDir=$CURRENT_LINE
            ROOT_HERE=0
        fi
        #echo string $CURRENT_LINE
        #CURRENT_SUBSTRING="--root"
        if test "$CURRENT_LINE" != "${CURRENT_LINE%$CURRENT_SUBSTRING*}"; then
            ROOT_HERE=1
        fi
        DELIMETER='='
        if test "$CURRENT_LINE" != "${CURRENT_LINE%$DELIMETER*}"; then
            #echo $CURRENT_LINE AAAA
            drupalDir=$(echo $CURRENT_LINE | awk -F \= '{print $2}')
            #echo $drupalDir
            break
        fi
    done
    if [ -n "$drupalDir" ]; then
        #echo root path $drupalDir
        break
    fi
done

# If no dir provided, use the current directory
if [ -z "$drupalDir" ]; then
    drupalDir=$(pwd)
fi

drush=$(findDrush "$drupalDir")
if [ -z "$drush" ]; then
    echo "Drush not found in $drupalDir."
    exit 1
fi
echo "### Drush Launcher. Dir: $drupalDir ###"
$(findDrush $drupalDir ) ${args}

