#!/bin/sh
echo "### Drush Launcher ###"
findDrush() {
    local ARGUMENT="$1"
    #echo ARGUMENT "$ARGUMENT"
    if [ -z "$ARGUMENT" ]; then
        local path=$(pwd)
        echo path pwd $path
    else
        local path="$ARGUMENT"
        #echo path ar $path
    fi

    #echo path
    # Check if the vendor/bin/drush directory exists in the current directory
    drushDir="$path/vendor/bin/drush"
    if [ -e "$drushDir" ]; then
        # Drush found, return the current directory
        echo "$drushDir"
        return
    fi

    # Move one level up the directory tree
    parentDir=$(dirname "$path")
    if [ "$parentDir" == "$path" ]; then
        # If we reached the root directory, stop traversing
        return
    fi

    # Check if the vendor/bin/drush directory exists in the parent directory
    drushDir="$parentDir/vendor/bin/drush"
    if [ -e "$drushDir" ]; then
        # Drush found in the parent directory, return the parent directory
        echo "$drushDir"
        return
    fi

    # Recursively continue searching in the parent directory
    findDrush "$parentDir"
}

#echo path to drush $(findDrush)
#echo ddd
#exit

#findDrush="/data/sites_php82/vendor/drush/drush/drush"

#args=("$@")
args="$*"
#echo "Args: " $args

COMMAND_ARGUMENTS="--root= --root -r= -r"
for CURRENT_SUBSTRING in ${COMMAND_ARGUMENTS}; do
    #echo QWE $CURRENT_SUBSTRING
    ROOT_HERE=0
    for CURRENT_LINE in ${args}; do
        if [ "$ROOT_HERE" = "1" ]; then
            ROOT_PATH=$CURRENT_LINE
            ROOT_HERE=0
        fi
        #echo string $CURRENT_LINE
        #CURRENT_SUBSTRING="--root"
        if test "$CURRENT_LINE" != "${CURRENT_LINE%$CURRENT_SUBSTRING*}"; then
            ROOT_HERE=1
        fi
        DELIMETER='='
        if test "$CURRENT_LINE" != "${CURRENT_LINE%$DELIMETER*}"; then
            #echo $CURRENT_LINE AAAA
            ROOT_PATH=$(echo $CURRENT_LINE | awk -F \= '{print $2}')
            #echo $ROOT_PATH
            break
        fi
    done
    if [ -n "$ROOT_PATH" ]; then
        #echo root path $ROOT_PATH
        break
    fi
done
echo Root path $ROOT_PATH



# If no dir provided, use the current directory
if [ -z "$ROOT_PATH" ]; then
    ROOT_PATH=$(pwd)
fi

echo "$ROOT_PATH"  


drush=$(findDrush "$ROOT_PATH")
if [ -z "$drush" ]; then
    echo "Drush not found in $ROOT_PATH."
    exit 1
fi



drush=$(findDrush "$ROOT_PATH")
echo AAA drush $drush

$(findDrush $ROOT_PATH ) ${args}
exit

#echo $drushDir
#/bin/sh -x
#a=`$findDrush ${ROOT_PATH}`
#$findDrush /data/sites_php82/modular.dev
#echo $a
#adfdfd=$($findDrush)
#echo $adfdfd  dd
#echo GG $drushDir
#$(findDrush gf) $args
#$(findDrush "/data/sites_php82/modular.dev") ggf  $args
#findDrush /data/sites_php82/modular.dev
#$findDrush /data/sites_php82/modular.dev/htdocs
#exit
#adfdfd=$($findDrush ${ROOT_PATH})
#echo $adfdfd  dd
#${adfdfd} $args
#echo $?
