#!/bin/sh
echo AA
findDrush() {
    local path=$(pwd)
    #echo path
    # Check if the vendor/bin/drush directory exists in the current directory
    drushDir="$path/vendor/bin/drush"
    if [ -e "$drushDir" ]; then
        # Drush found, return the current directory
        echo "$drushDir"
        return
    fi

    # Move one level up the directory tree
    parentDir=$(dirname "$path")
    if [ "$parentDir" == "$path" ]; then
        # If we reached the root directory, stop traversing
        return
    fi

    # Check if the vendor/bin/drush directory exists in the parent directory
    drushDir="$parentDir/vendor/bin/drush"
    if [ -e "$drushDir" ]; then
        # Drush found in the parent directory, return the parent directory
        echo "$drushDir"
        return
    fi

    # Recursively continue searching in the parent directory
    findDrush "$parentDir"
}

echo path to drush $(findDrush)
#echo ddd
#exit

#findDrush="/data/sites_php82/vendor/drush/drush/drush"

#args=("$@")
args="$*"
echo "Args: " $args

COMMAND_ARGUMENTS="--root= --root -r= -r"
for CURRENT_SUBSTRING in ${COMMAND_ARGUMENTS}; do
    echo QWE $CURRENT_SUBSTRING
    ROOT_HERE=0
    for CURRENT_LINE in ${args}; do
        if [ "$ROOT_HERE" = "1" ]; then
            ROOT_PATH=$CURRENT_LINE
            ROOT_HERE=0
        fi
        echo string $CURRENT_LINE
        #CURRENT_SUBSTRING="--root"
        if test "$CURRENT_LINE" != "${CURRENT_LINE%$CURRENT_SUBSTRING*}"; then
            ROOT_HERE=1
        fi
        DELIMETER='='
        if test "$CURRENT_LINE" != "${CURRENT_LINE%$DELIMETER*}"; then
            echo $CURRENT_LINE AAAA
            ROOT_PATH=$(echo $CURRENT_LINE | awk -F \= '{print $2}')
            echo $ROOT_PATH
            break
        fi
    done
    if [ -n "$ROOT_PATH" ]; then
        echo root path $ROOT_PATH
        break
    fi

done

#exit

#echo GG $drushDir
$(findDrush) $args
